name: push-release
run-name: "ビルドしてリリース"
on:
  push:
    paths:
      - src/**
      - .github/workflows/release.yml
jobs:
  linux:
    name: "Build & Upload Linux"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
      - name: "Install Packages on yarn"
        run: yarn install
      - name: "Build"
        run: yarn make
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "linux"
          path: "out/**"
  windows:
    name: "Build & Upload Windows"
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
      - name: "Install Packages on yarn"
        run: yarn install
      - name: "Build"
        run: yarn make
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "windows"
          path: "out/**"
  macos:
    name: "Build & Upload Mac"
    runs-on: macos-14
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
      - name: "Install Packages on yarn"
        run: yarn install
      - name: "Build"
        run: yarn make
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "macos"
          path: "out/**"
